// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using SmartEduPro.Infrastructure.Persistence;

#nullable disable

namespace SmartEduPro.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722152724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Activity_Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Ip_Address")
                        .HasColumnType("text");

                    b.Property<Guid?>("Target_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Target_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Activity_Logs");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Author_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Expires_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Pinned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Published_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Send_Push")
                        .HasColumnType("boolean");

                    b.Property<bool>("Send_Sms")
                        .HasColumnType("boolean");

                    b.Property<bool>("Send_Whatsapp")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("Target_Class_Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Target_Role")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Attendance_Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Check_In_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Check_Out_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Late_Minutes")
                        .HasColumnType("integer");

                    b.Property<string>("Marked_Via")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Notified_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Parent_Notified")
                        .HasColumnType("boolean");

                    b.Property<string>("Qr_Scan_Log")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Session_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Session_Id");

                    b.HasIndex("Student_Id");

                    b.ToTable("Attendance_Records");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Attendance_Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Class_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("End_Time")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Completed")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Session_Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Start_Time")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("Subject_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Teacher_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Total_Absent")
                        .HasColumnType("integer");

                    b.Property<int>("Total_Late")
                        .HasColumnType("integer");

                    b.Property<int>("Total_Present")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Class_Id");

                    b.HasIndex("Institute_Id");

                    b.HasIndex("Subject_Id");

                    b.HasIndex("Teacher_Id");

                    b.ToTable("Attendance_Sessions");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Billing_Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount_Lkr")
                        .HasColumnType("numeric");

                    b.Property<NpgsqlRange<DateTime>>("BillingPeriod")
                        .HasColumnType("tstzrange");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Invoice_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payment_Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payment_Ref")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Billing_Transactions");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Manager_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Institute_Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Academic_year")
                        .HasColumnType("integer");

                    b.Property<int>("Al_Stream")
                        .HasColumnType("integer");

                    b.Property<Guid>("Branch_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Class_Type")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Max_Student")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Study_Level")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Branch_Id");

                    b.HasIndex("Institute_Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Class_Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Class_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monthly_Fee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("Subject_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Teacher_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Class_Subjects");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Class_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration_Min")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Exam_Date")
                        .HasColumnType("date");

                    b.Property<int>("Exam_Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_Published")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Pass_Mark")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Published_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("Start_Time")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("Subject_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Teacher_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Total_Mark")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Class_Id");

                    b.HasIndex("Institute_Id");

                    b.HasIndex("Subject_Id");

                    b.HasIndex("Teacher_Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Exam_Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Exam_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("Is_Absent")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Marks_Obtained")
                        .HasColumnType("numeric");

                    b.Property<bool>("Parent_Notified")
                        .HasColumnType("boolean");

                    b.Property<int>("Rank_Int_Class")
                        .HasColumnType("integer");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Teacher_Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Exam_Id");

                    b.HasIndex("Student_Id");

                    b.ToTable("Exam_Results");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Fee_Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount_Lkr")
                        .HasColumnType("numeric");

                    b.Property<string>("Billing_Cycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Class_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Due_Day")
                        .HasColumnType("integer");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Late_Fee_Lkr")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Class_Id");

                    b.HasIndex("Institute_Id");

                    b.ToTable("Fee_Packages");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Fee_Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount_Lkr")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Fee_Record_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Payment_Date")
                        .HasColumnType("date");

                    b.Property<int>("Payment_Method")
                        .HasColumnType("integer");

                    b.Property<string>("Payment_Ref")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Receipt_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Receipt_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Received_By")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Fee_Record_Id");

                    b.HasIndex("Institute_Id");

                    b.HasIndex("Received_By");

                    b.HasIndex("Student_Id");

                    b.ToTable("Fee_Payments");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Institute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address_Line1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address_Line2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deleted_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Max_Teacher")
                        .HasColumnType("integer");

                    b.Property<int>("Max_student")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner_Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner_Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Postal_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Registration_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Subscription_End")
                        .HasColumnType("date");

                    b.Property<int>("Subscription_Plan")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Subscription_Start")
                        .HasColumnType("date");

                    b.Property<int>("Subscription_Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Trial_End")
                        .HasColumnType("date");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Institute_Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Branch_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Institute_Admins");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount_Lkr")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Due_Date")
                        .HasColumnType("date");

                    b.Property<Guid>("Fee_Record_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Invoice_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Issued_Date")
                        .HasColumnType("date");

                    b.Property<string>("Pdf_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sent_Via")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Fee_Record_Id");

                    b.HasIndex("Institute_Id");

                    b.HasIndex("Student_Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Learning_Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Class_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Download_Count")
                        .HasColumnType("integer");

                    b.Property<decimal?>("File_Size_Mb")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("File_Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("File_Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Published")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("Subject_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("Uploaded_By")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Class_Id");

                    b.HasIndex("Institute_Id");

                    b.HasIndex("Subject_Id");

                    b.HasIndex("Uploaded_By");

                    b.ToTable("Learning_Resources");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Live_Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("Actual_End")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Actual_Start")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("Chat_Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Class_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Join_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Participant_Count")
                        .HasColumnType("integer");

                    b.Property<int>("Peak_Viewers")
                        .HasColumnType("integer");

                    b.Property<bool>("Recording_Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Recording_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room_Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Scheduled_End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Scheduled_Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Subject_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Teacher_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeTable_Slot_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhiteBoard_Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Live_Sessions");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Live_Session_Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Duration_Secs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Joined_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Left_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Session_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Session_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Live_Session_Participants");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attachment_Url")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Read")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Read_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Recipient_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Sender_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Delivered_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Delivery_Error")
                        .HasColumnType("text");

                    b.Property<Guid?>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Delivered")
                        .HasColumnType("boolean");

                    b.Property<bool>("Is_Read")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Read_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Recipient_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Notification_Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body_Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Title_Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notification_Templates");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Otp_Code", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Otp_Codes");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Alt_Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Preffered_Channel")
                        .HasColumnType("integer");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Whatsapp_No")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Class_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration_Sec")
                        .HasColumnType("integer");

                    b.Property<decimal>("File_Size_Mb")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("File_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Published")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Recorded_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Session_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Subject_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Teacher_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Thumbnail_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("View_Count")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Class_Id");

                    b.HasIndex("Institute_Id");

                    b.HasIndex("Session_Id");

                    b.HasIndex("Subject_Id");

                    b.HasIndex("Teacher_Id");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Refresh_Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Device_Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expire_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("Ip_Address")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<DateTime>("Revoked_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token_Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Refresh_Tokens");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date_Of_Birth")
                        .HasColumnType("date");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("Enrolled_At")
                        .HasColumnType("date");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Guardian_Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Guardian_Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Guardian_Relation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Home_Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Nic_Or_Birth_Cert")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Photo_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Qr_Code_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Qr_Secret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("School_Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Student_No")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Student_Class_Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Class_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Enrolled_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Fee_Package_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Left_Date")
                        .HasColumnType("date");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Student_Class_Enrollments");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Student_Fee_Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount_Due")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("Billing_Month")
                        .HasColumnType("date");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("Due_Date")
                        .HasColumnType("date");

                    b.Property<Guid>("Fee_Package_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Fee_Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Last_Reminder_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Late_Fee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reminder_Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Fee_Package_Id");

                    b.HasIndex("Institute_Id");

                    b.HasIndex("Student_Id");

                    b.ToTable("Student_Fee_Records");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Student_Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Is_Primary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Parent_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Parent_Id");

                    b.HasIndex("Student_Id");

                    b.ToTable("Student_Parents");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Student_Qr_Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Last_Used_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Qr_Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Student_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Student_Id");

                    b.ToTable("Student_Qr_Tokens");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Al_Stream")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Insitute_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstitutesId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Study_Level")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstitutesId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Subscription_Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Display_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<int>("Max_Branch")
                        .HasColumnType("integer");

                    b.Property<int>("Max_Student")
                        .HasColumnType("integer");

                    b.Property<int>("Max_Teacher")
                        .HasColumnType("integer");

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price_Lkr")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Subscription_Plans");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bank_Account")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bank_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date_Of_Birth")
                        .HasColumnType("date");

                    b.Property<int>("Experience_Yrs")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Joined_Date")
                        .HasColumnType("date");

                    b.Property<string>("Nic")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Photo_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary_Lkr")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Teacher_No")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Teacher_Class_Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Class_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("From_Date")
                        .HasColumnType("date");

                    b.Property<bool>("Is_Primary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Subject_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Teacher_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("To_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Teacher_Class_Assignments");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Timetable_Override", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Created_By")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("New_End_Time")
                        .HasColumnType("time without time zone");

                    b.Property<string>("New_Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("New_Start_Time")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("Notify_Student")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Override_Date")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Time_Table_Slot_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Created_By");

                    b.HasIndex("Time_Table_Slot_Id");

                    b.ToTable("Timetable_Overrides");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Timetable_Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Branch_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Class_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Class_Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Day_Of_Week")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Effective_From")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Effective_To")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("End_Time")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("Institute_Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("Start_Time")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("Subject_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Teacher_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Branch_Id");

                    b.HasIndex("Class_Id");

                    b.HasIndex("Institute_Id");

                    b.HasIndex("Subject_Id");

                    b.ToTable("Timetable_Slots");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apns_Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Avatar_Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deleted_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fcm_Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("Is_Verified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Last_Login_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Preferred_Lan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Attendance_Record", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Attendance_Session", "Attendance_Sessions")
                        .WithMany()
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Student", "Students")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance_Sessions");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Attendance_Session", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Class", "Classes")
                        .WithMany()
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Subject", "Subjects")
                        .WithMany()
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Teacher", "Teachers")
                        .WithMany()
                        .HasForeignKey("Teacher_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Institutes");

                    b.Navigation("Subjects");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Branch", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institutes");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Class", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Branch", "Branches")
                        .WithMany()
                        .HasForeignKey("Branch_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branches");

                    b.Navigation("Institutes");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Exam", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Class", "Classes")
                        .WithMany()
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Subject", "Subjects")
                        .WithMany()
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Teacher", "Teachers")
                        .WithMany()
                        .HasForeignKey("Teacher_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Institutes");

                    b.Navigation("Subjects");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Exam_Result", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Exam", "Exams")
                        .WithMany()
                        .HasForeignKey("Exam_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Student", "Students")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exams");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Fee_Package", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Class", "Classes")
                        .WithMany()
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Institutes");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Fee_Payment", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Student_Fee_Record", "Fee_Records")
                        .WithMany()
                        .HasForeignKey("Fee_Record_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("Received_By")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Student", "Students")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fee_Records");

                    b.Navigation("Institutes");

                    b.Navigation("Students");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Student_Fee_Record", "Fee_Records")
                        .WithMany()
                        .HasForeignKey("Fee_Record_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Student", "Students")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fee_Records");

                    b.Navigation("Institutes");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Learning_Resource", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Class", "Classes")
                        .WithMany()
                        .HasForeignKey("Class_Id");

                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Subject", "Subjects")
                        .WithMany()
                        .HasForeignKey("Subject_Id");

                    b.HasOne("SmartEduPro.Domain.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("Uploaded_By")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Institutes");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Live_Session_Participant", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Live_Session", "Live_Sessions")
                        .WithMany()
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Live_Sessions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Recording", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Class", "Classes")
                        .WithMany()
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Live_Session", "Sessions")
                        .WithMany()
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Subject", "Subjects")
                        .WithMany()
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Teacher", "Teachers")
                        .WithMany()
                        .HasForeignKey("Teacher_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classes");

                    b.Navigation("Institutes");

                    b.Navigation("Sessions");

                    b.Navigation("Subjects");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Refresh_Token", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Student", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Student_Fee_Record", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Fee_Package", "Fee_Packages")
                        .WithMany()
                        .HasForeignKey("Fee_Package_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Student", "Students")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fee_Packages");

                    b.Navigation("Institutes");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Student_Parent", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Parent", "Parents")
                        .WithMany()
                        .HasForeignKey("Parent_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Student", "Students")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parents");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Student_Qr_Token", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Student", "Students")
                        .WithMany()
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Subject", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("InstitutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institutes");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Timetable_Override", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Timetable_Slot", "TimeTable_Slots")
                        .WithMany()
                        .HasForeignKey("Time_Table_Slot_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeTable_Slots");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartEduPro.Domain.Entities.Timetable_Slot", b =>
                {
                    b.HasOne("SmartEduPro.Domain.Entities.Branch", "Branches")
                        .WithMany()
                        .HasForeignKey("Branch_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Class", "Classes")
                        .WithMany()
                        .HasForeignKey("Class_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Institute", "Institutes")
                        .WithMany()
                        .HasForeignKey("Institute_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartEduPro.Domain.Entities.Subject", "Subjects")
                        .WithMany()
                        .HasForeignKey("Subject_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branches");

                    b.Navigation("Classes");

                    b.Navigation("Institutes");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
